/**
 * AFREELEO Mission Configuration
 *
 * This file contains paths to mission trajectory files generated by
 * the afro-launch-cost_calculator repository.
 *
 * These files are generated from GMAT (General Mission Analysis Tool) simulations.
 */

export const MISSION_CONFIGURATION = {
  // Mission trajectory files generated by afro-launch-cost_calculator
  trajectoryFiles: {
    // Upper stage trajectory file
    upperstage: './mission_38baa6d1_upperstage.txt',

    // Satellite trajectory file
    satellite: './mission_38baa6d1_satellite.txt',
  }
};
